; Tox config
[tox]
envlist = ruff, mypy, py39, py310, py311, py312, py313, py314
; envlist = py312
skipsdist = true

[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: ruff, mypy, py312
    3.13: py313
    3.14: py314

; Test config
[testenv]
allowlist_externals = poetry
commands_pre =
    poetry sync
commands =
    poetry run pytest --cov-config=tox.ini --cov=hvcc tests/

[testenv:ruff]
allowlist_externals = poetry
commands_pre =
    poetry sync --with dev
commands =
    poetry run ruff check .

[testenv:mypy]
allowlist_externals = poetry
commands_pre =
    poetry sync --with dev
commands =
    poetry run mypy hvcc

[run]
ignore = examples/*
cov-report = html,term
omit = .tox/*,.venv/*,venv/*,tests/*,examples/*,setup.py

[ruff]
line-length = 120
exclude = .tox,.venv,venv,build,examples,hvcc/generators/ir2c/static/MicroNam/*
